name: Run Tests

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - run: npm ci
      - run: npm run lint
      - run: npm test
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - run: npm ci
      - name: Generate SDK for E2E tests
        run: |
          npm run dev -- ./tests/e2e/schema.json ./tests/e2e/single/sdk.ts --disable-analytics --mode single
          npm run dev -- ./tests/e2e/schema.json ./tests/e2e/split/sdk.ts --disable-analytics --mode split
          npm run dev -- ./tests/e2e/schema.json ./tests/e2e/tags/sdk.ts --disable-analytics --mode tags
      - name: Start Mockoon CLI
        uses: mockoon/cli-action@v2
        with:
          # Mockoon local data file or URL
          data-file: './tests/e2e/schema.json'
          port: 3000
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        with:
          path: './tests/e2e/*/k6Script.ts'
          flags: '--compatibility-mode=experimental_enhanced'
          inspect-flags: '--compatibility-mode=experimental_enhanced'
  run-examples:
    runs-on: ubuntu-latest
    needs: [test, e2e-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21.5.0'
      - run: npm ci
      - name: Update examples
        run: npm run update-examples
      - name: Compare generated Clients with existing ones
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol --text examples/ | wc -l)" -gt "0" ]; then
            echo "Detected changes in the examples, run `npm run update-examples` to update all the examples."
            git diff --ignore-space-at-eol --text examples/
            exit 1
          fi
